version: "3"
services:
  alpine-spark:
    image: aktechthoughts/alpine-spark:1
    build: .
    volumes:
    - ./app:/app
    - ./conf:/usr/spark-2.4.6/conf

  master:
    image: aktechthoughts/pyspark_master
    build:
     context: .
     dockerfile: spark.Dockerfile
    depends_on:
     - alpine-spark
    command:
      ["/usr/spark-2.4.6/bin/spark-class", "org.apache.spark.deploy.master.Master"]
    hostname: master
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /usr/spark-2.4.6/conf
    expose:
      - 7001
      - 7002
      - 7003
      - 7004
      - 7005
      - 7006
      - 7077
      - 6066
    ports:
      - 4040:4040
      - 6066:6066
      - 7077:7077
      - 8080:8080
    volumes:
      - ./conf/master:/usr/spark-2.4.6/conf
      - ./app:/app

  worker:
    image: aktechthoughts/pyspark_worker
    build:
     context: .
     dockerfile: spark.Dockerfile
    command:
      [
        "/usr/spark-2.4.6/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://master:7077",
      ]
    hostname: worker
    environment:
      MASTER: spark://master:7077
      SPARK_CONF_DIR: /conf
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 1g
      SPARK_WORKER_PORT: 8881
      SPARK_WORKER_WEBUI_PORT: 8081
    depends_on:
      - master
    expose:
      - 7012
      - 7013
      - 7014
      - 7015
      - 7016
      - 8881
    ports:
      - 8081:8081
    volumes:
      - ./conf/worker:/usr/spark-2.4.6/conf
      - ./app:/app

#  jupyter:
#  client:
#    image: eipdev/alpine-jupyter-notebook
#    ports:
#      - 8888:8888
